const testData = [
  {
    title: "Oliver Anthony - Rich Men North Of Richmond",
    description:
      "When I first came across Oliver Anthony and his music, I was blown away to say the least.  He had a whole collection of songs that I could listen to for hours.  Oliver resides in Farmville,...",
    publishedDate: "2023-08-22T14:54:56.165Z",
    publishedText: "2 weeks ago",
    videoId: "sqSA-SY5Hro",
    videoUrl: "https://youtube.com/watch?v=sqSA-SY5Hro",
    channelName: "radiowv",
    channelId: "UCrZb1efgWeZnqn-YPzQTvJw",
    channelUrl: "https://youtube.com/@radiowv",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/sqSA-SY5Hro/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 36550345,
    viewsText: "36,550,345 views",
    duration: 191,
    durationText: "3:11",
    verified: false,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Rod Wave - Call Your Friends (Official Video)",
    description:
      'Listen to Rod Wave "Call Your Friends" On All Platforms:\nhttps://rodwave.lnk.to/CallYourFriends\n\nFollow Rod Wave:\n► Instagram: https://www.instagram.com/rodwave/\n► Twitter: https://twitter.com/...',
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "kC8YEw9h2-Q",
    videoUrl: "https://youtube.com/watch?v=kC8YEw9h2-Q",
    channelName: "RodWave",
    channelId: "UCenjunBhBhvKjfDAESnoppw",
    channelUrl: "https://youtube.com/channel/UCenjunBhBhvKjfDAESnoppw",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/kC8YEw9h2-Q/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 4541506,
    viewsText: "4,541,506 views",
    duration: 154,
    durationText: "2:34",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Lil Durk - F*ck U Thought (Official Video)",
    description:
      'Shot by @JerryPHD \n\n"F*ck You Thought" by Lil Durk. Out Now:\nhttps://LilDurk.lnk.to/FYT\n\nAlmost Healed, the new album from Lil Durk. Out Now:\nhttps://LilDurk.lnk.to/AlmostHealed\n\nTour On Sale...',
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "-jEShhcnxIM",
    videoUrl: "https://youtube.com/watch?v=-jEShhcnxIM",
    channelName: "Lil Durk",
    channelId: "UCaxOQZrF5llUMp-JjesUz1A",
    channelUrl: "https://youtube.com/channel/UCaxOQZrF5llUMp-JjesUz1A",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/-jEShhcnxIM/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 3157663,
    viewsText: "3,157,663 views",
    duration: 196,
    durationText: "3:16",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "KAROL G - MI EX TENÍA RAZÓN (Official Video)",
    description:
      "Escucha / Stream “MAÑANA SERÁ BONITO (BICHOTA SEASON)” on your favorite platform: https://KarolG.lnk.to/BichotaSeason\n\nSubscribe to my YouTube channel here: https://karolg.lnk.to/SubscribeKar...",
    publishedDate: "2023-08-22T19:42:56.165Z",
    publishedText: "12 days ago",
    videoId: "VBcs8DZxBGc",
    videoUrl: "https://youtube.com/watch?v=VBcs8DZxBGc",
    channelName: "KAROL G",
    channelId: "UCZuPJZ2kGFdlbQu1qotZaHw",
    channelUrl: "https://youtube.com/channel/UCZuPJZ2kGFdlbQu1qotZaHw",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/VBcs8DZxBGc/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 45449248,
    viewsText: "45,449,248 views",
    duration: 162,
    durationText: "2:42",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Usher - Boyfriend (Official Music Video)",
    description:
      "Listen to USHER’s “Boyfriend”: https://vydia.lnk.to/Boyfriend\n \nFollow USHER \nTikTok https://www.tiktok.com/@usher\nInstagram https://www.instagram.com/usher/\nTwitter https://twitter.com...",
    publishedDate: "2023-08-23T07:42:56.165Z",
    publishedText: "7 days ago",
    videoId: "56CW4SIqBzk",
    videoUrl: "https://youtube.com/watch?v=56CW4SIqBzk",
    channelName: "Usher",
    channelId: "UCaNrhBiXsXIM2epDl_kEzgQ",
    channelUrl: "https://youtube.com/channel/UCaNrhBiXsXIM2epDl_kEzgQ",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/56CW4SIqBzk/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 4144683,
    viewsText: "4,144,683 views",
    duration: 277,
    durationText: "4:37",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Polo G - Barely Holdin' On (Official Video)",
    description:
      "Official Music Video for “Barely Holdin' On” by Polo G\n \nListen & Download “Barely Holdin' On” by Polo G out now: https://polog.lnk.to/BarelyHoldinOn\n \nAmazon Music - https://polog.lnk.to/B...",
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "JCf7jrglH6A",
    videoUrl: "https://youtube.com/watch?v=JCf7jrglH6A",
    channelName: "Polo G",
    channelId: "UC0ifXd2AVf1LMYbqwB5GH4g",
    channelUrl: "https://youtube.com/channel/UC0ifXd2AVf1LMYbqwB5GH4g",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/JCf7jrglH6A/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 3392339,
    viewsText: "3,392,339 views",
    duration: 256,
    durationText: "4:16",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Sexyy Red & Sukihana - Hood Rats (Official Video)",
    description:
      'Stream "Hood Rats" here: https://openshiftdistro.lnk.to/HoodRats\n\nFollow Sexyy Red here: https://instagram.com/sexyyred314?utm_medium=copy_link\nTik Tok: http://www.tiktok.com/@sexyyred314\nTwitter:...',
    publishedDate: "2023-08-23T07:42:56.165Z",
    publishedText: "7 days ago",
    videoId: "S2sHaMnhIcs",
    videoUrl: "https://youtube.com/watch?v=S2sHaMnhIcs",
    channelName: "Sexyy Red",
    channelId: "UC28rc3PHWPJib68G-VqpJ3w",
    channelUrl: "https://youtube.com/channel/UC28rc3PHWPJib68G-VqpJ3w",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/S2sHaMnhIcs/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 1606952,
    viewsText: "1,606,952 views",
    duration: 366,
    durationText: "6:06",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "KAROL G, Peso Pluma - QLONA (Visualizer)",
    description:
      "Escucha / Stream “MAÑANA SERÁ BONITO (BICHOTA SEASON)” on your favorite platform: https://KarolG.lnk.to/BichotaSeason\n\nSubscribe to my YouTube channel here: https://karolg.lnk.to/SubscribeKar...",
    publishedDate: "2023-08-22T19:42:56.165Z",
    publishedText: "12 days ago",
    videoId: "BeUOBoSPWvA",
    videoUrl: "https://youtube.com/watch?v=BeUOBoSPWvA",
    channelName: "KAROL G",
    channelId: "UCZuPJZ2kGFdlbQu1qotZaHw",
    channelUrl: "https://youtube.com/channel/UCZuPJZ2kGFdlbQu1qotZaHw",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/BeUOBoSPWvA/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 18073802,
    viewsText: "18,073,802 views",
    duration: 173,
    durationText: "2:53",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Chris Brown - Summer Too Hot (Official Video)",
    description:
      "Chris Brown - “Summer Too Hot” Out Now!\nListen Here: https://chrisbrown.lnk.to/summertoohot\n \nLyrics: \nSummer too hot \n\nI blew it all on her \nI get it right back \nShe put it all on me ...",
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "qxTqRFSWmm8",
    videoUrl: "https://youtube.com/watch?v=qxTqRFSWmm8",
    channelName: "Chris Brown",
    channelId: "UCcYrdFJF7hmPXRNaWdrko4w",
    channelUrl: "https://youtube.com/channel/UCcYrdFJF7hmPXRNaWdrko4w",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/qxTqRFSWmm8/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 3761223,
    viewsText: "3,761,223 views",
    duration: 227,
    durationText: "3:47",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Victoria Monét - On My Mama (Official Video)",
    description:
      'Listen to "On My Mama" Here: \nhttps://victoriamonet.lnk.to/onmymama\n\nFollow Victoria Monét:\nInstagram: https://www.instagram.com/victoriamon...\nTikTok: https://www.tiktok.com/@victoriamonet...',
    publishedDate: "2023-08-23T05:18:56.165Z",
    publishedText: "8 days ago",
    videoId: "KdJ-Qwu3y4Y",
    videoUrl: "https://youtube.com/watch?v=KdJ-Qwu3y4Y",
    channelName: "Victoria Monét",
    channelId: "UCF-Gj_k3Uk4WnK2UhJcSzYg",
    channelUrl: "https://youtube.com/channel/UCF-Gj_k3Uk4WnK2UhJcSzYg",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/KdJ-Qwu3y4Y/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 2353567,
    viewsText: "2,353,567 views",
    duration: 217,
    durationText: "3:37",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Olivia Rodrigo - bad idea right? (Official Video)",
    description:
      "Listen to bad idea right? out now: https://OliviaRodrigo.lnk.to/badidearight\n \nStore: https://OliviaRodrigo.lnk.to/store\n \nFollow Olivia Rodrigo:\nInstagram: https://instagram.com/oliviarodrigo...",
    publishedDate: "2023-08-22T19:42:56.165Z",
    publishedText: "12 days ago",
    videoId: "Dj9qJsJTsjQ",
    videoUrl: "https://youtube.com/watch?v=Dj9qJsJTsjQ",
    channelName: "Olivia Rodrigo",
    channelId: "UCy3zgWom-5AGypGX_FVTKpg",
    channelUrl: "https://youtube.com/channel/UCy3zgWom-5AGypGX_FVTKpg",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/Dj9qJsJTsjQ/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 10140757,
    viewsText: "10,140,757 views",
    duration: 191,
    durationText: "3:11",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "La 701",
    description:
      "Provided to YouTube by TuneCore\n\nLa 701 · Panter Bélico\n\nLa 701\n\n℗ 2023 Belikiki Music\n\nReleased on: 2023-07-07\n\nAuto-generated by YouTube.",
    publishedDate: "2023-08-23T22:06:56.165Z",
    publishedText: "1 day ago",
    videoId: "iB3y3U5O9WA",
    videoUrl: "https://youtube.com/watch?v=iB3y3U5O9WA",
    channelName: "Panter Bélico - Topic",
    channelId: "UCkWw_xtIo61-Ty16MlWL-DA",
    channelUrl: "https://youtube.com/channel/UCkWw_xtIo61-Ty16MlWL-DA",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/iB3y3U5O9WA/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 437862,
    viewsText: "437,862 views",
    duration: 181,
    durationText: "3:01",
    verified: false,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: 'JIHYO "Killin\' Me Good" M/V',
    description:
      'JIHYO "Killin\' Me Good" M/V\n\nJIHYO The 1st Mini Album "ZONE"\n\n🔥Listen "Killin\' Me Good"\nhttps://jihyo.lnk.to/ZONE\n\nTWICE Official Shop: https://TWICE.lnk.to/Shop\nTWICE Official YouTube:...',
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "jyw_vrI4ySg",
    videoUrl: "https://youtube.com/watch?v=jyw_vrI4ySg",
    channelName: "JYP Entertainment",
    channelId: "UCaO6TYtlC8U5ttz62hTrZgg",
    channelUrl: "https://youtube.com/@JYPEntertainment",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/jyw_vrI4ySg/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 9286180,
    viewsText: "9,286,180 views",
    duration: 210,
    durationText: "3:30",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title:
      "Kyle Gordon - Planet of the Bass (feat. DJ Crazy Times & Ms. Biljana Electronica) [Official Video]",
    description:
      "Official music video for Kyle Gordon’s “Planet of the Bass (feat. DJ Crazy Times & Ms. Biljana Electronica)”.\n\nListen to “Planet of the Bass”: https://kylegordon.lnk.to/PlanetOfTheBassID...",
    publishedDate: "2023-08-23T05:18:56.165Z",
    publishedText: "8 days ago",
    videoId: "S-OgkNgxm3k",
    videoUrl: "https://youtube.com/watch?v=S-OgkNgxm3k",
    channelName: "kylegordonisgreat",
    channelId: "UCokXg7-kW6cA_WDe6JPuM9g",
    channelUrl: "https://youtube.com/@kylegordonisgreat8611",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/S-OgkNgxm3k/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 1955411,
    viewsText: "1,955,411 views",
    duration: 209,
    durationText: "3:29",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Ciara, Lil Baby - Forever",
    description:
      "CiCi available everywhere: https://vydia.lnk.to/CiCi\n\nFollow Ciara Everywhere:\nInstagram: instagram.com/ciara\nTikTok: https://www.tiktok.com/@ciara\nTwitter: https://twitter.com/ciara\nFacebook:...",
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "4SvZIsYffNk",
    videoUrl: "https://youtube.com/watch?v=4SvZIsYffNk",
    channelName: "Ciara",
    channelId: "UClc5Eis2-L2JCcN62jmD21w",
    channelUrl: "https://youtube.com/channel/UClc5Eis2-L2JCcN62jmD21w",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/4SvZIsYffNk/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 1486606,
    viewsText: "1,486,606 views",
    duration: 213,
    durationText: "3:33",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "La 701",
    description:
      "Provided to YouTube by DistroKid\n\nLa 701 · Alex Tumbado\n\nLa 701\n\n℗ Meñiza Records\n\nReleased on: 2023-08-20\n\nAuto-generated by YouTube.",
    publishedDate: "2023-08-23T19:42:56.165Z",
    publishedText: "2 days ago",
    videoId: "QaMdgMvL_x8",
    videoUrl: "https://youtube.com/watch?v=QaMdgMvL_x8",
    channelName: "Alex Tumbado - Topic",
    channelId: "UCijinLqqxXMN4v9JTCSSK1A",
    channelUrl: "https://youtube.com/channel/UCijinLqqxXMN4v9JTCSSK1A",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/QaMdgMvL_x8/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 614424,
    viewsText: "614,424 views",
    duration: 181,
    durationText: "3:01",
    verified: false,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Brent Faiyaz - JACKIE BROWN [Official Video]",
    description:
      '"JACKIE BROWN" by BRENT FAIYAZ\n\ndirector: Lonewolf & Mark Peaced\neditor: Lonewolf\nproduction co : BT Studios \nexecutive producers : Carlos Lopes, Galileo Mondol \nproducer : Tali Weizman, Alex...',
    publishedDate: "2023-08-23T07:42:56.165Z",
    publishedText: "7 days ago",
    videoId: "2kD3BczXH9M",
    videoUrl: "https://youtube.com/watch?v=2kD3BczXH9M",
    channelName: "Brent Faiyaz",
    channelId: "UCtdVC7nSYNOpKroA5JicNig",
    channelUrl: "https://youtube.com/channel/UCtdVC7nSYNOpKroA5JicNig",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/2kD3BczXH9M/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 1182257,
    viewsText: "1,182,257 views",
    duration: 191,
    durationText: "3:11",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title:
      "Ryan Gosling - I'm Just Ken Exclusive (From Barbie The Album) [Official]",
    description:
      "Barbie The Album Available Everywhere + Barbie In Theaters Now!\nDownload/Stream: https://barbiethealbum.lnk.to/BTA\n\nFollow Barbie The Album: \nhttps://www.instagram.com/barbiethealbum/\nhttps://tikto...",
    publishedDate: "2023-08-23T19:42:56.165Z",
    publishedText: "2 days ago",
    videoId: "ru1LC9lW20Q",
    videoUrl: "https://youtube.com/watch?v=ru1LC9lW20Q",
    channelName: "Atlantic Records",
    channelId: "UCe4LM_eKc9ywRmVuBm5pjQg",
    channelUrl: "https://youtube.com/@atlanticrecords",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/ru1LC9lW20Q/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 2001253,
    viewsText: "2,001,253 views",
    duration: 232,
    durationText: "3:52",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: 'Tom MacDonald & Adam Calhoun - "Your America"',
    description:
      'DOWNLOAD "Your America": https://geo.itunes.apple.com/us/album/your-america-single/1701433643?ls=1&app=itunes\nPRE-ORDER "The Brave 2": https://vydia.lnk.to/TheBrave2\n\nTom MacDonald & Adam Calhoun...',
    publishedDate: "2023-08-22T19:42:56.165Z",
    publishedText: "12 days ago",
    videoId: "K1uqe6GQdbU",
    videoUrl: "https://youtube.com/watch?v=K1uqe6GQdbU",
    channelName: "Adam Calhoun",
    channelId: "UC8Yx90YfnpSTXApA9_rYX-g",
    channelUrl: "https://youtube.com/channel/UC8Yx90YfnpSTXApA9_rYX-g",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/K1uqe6GQdbU/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 4641669,
    viewsText: "4,641,669 views",
    duration: 189,
    durationText: "3:09",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Oliver Anthony - Rich Men North of Richmond (Lyrics)",
    description:
      '» Connect with Oliver Anthony: https://www.instagram.com/oliver_anthony_music_/\n» Watch the radiowv live session: https://www.youtube.com/watch?v=sqSA-SY5Hro\n\n» Lyrics for "Rich Men North...',
    publishedDate: "2023-08-23T00:30:56.165Z",
    publishedText: "10 days ago",
    videoId: "mipujcSZrJs",
    videoUrl: "https://youtube.com/watch?v=mipujcSZrJs",
    channelName: "SauceOnly",
    channelId: "UCcJZ-w0N3-Z2jnJ8UgoBclQ",
    channelUrl: "https://youtube.com/@SauceOnly",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/mipujcSZrJs/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 1362331,
    viewsText: "1,362,331 views",
    duration: 188,
    durationText: "3:08",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title:
      "Grupo Frontera x Grupo Firme - EL AMOR DE SU VIDA (Video Oficial) | El Comienzo",
    description:
      "Escucha nuestro álbum “El Comienzo” aquí: https://bit.ly/ElComienzoGF\nGrupo Frontera x Grupo Firme - EL AMOR DE SU VIDA (Video Oficial)\nSuscríbete a nuestro canal: https://bit.ly/GrupoFronte...",
    publishedDate: "2023-08-22T14:54:56.165Z",
    publishedText: "2 weeks ago",
    videoId: "Vr1M_l-1wjc",
    videoUrl: "https://youtube.com/watch?v=Vr1M_l-1wjc",
    channelName: "Grupo Frontera",
    channelId: "UCKsN6xyJ2w8g7p4p9apXkYQ",
    channelUrl: "https://youtube.com/channel/UCKsN6xyJ2w8g7p4p9apXkYQ",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/Vr1M_l-1wjc/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 32229049,
    viewsText: "32,229,049 views",
    duration: 173,
    durationText: "2:53",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "EST Gee, Lil Baby - I THINK (Official Music Video)",
    description:
      "Stream 'El Toro 2' now: https://estgee.lnk.to/ElToro2\n\nFollow EST Gee:\nhttps://twitter.com/ESTGEE\nhttps://www.instagram.com/est.gee\nhttps://www.facebook.com/ESTGeeOffici...\nhttps://smarturl.it/ESTG...",
    publishedDate: "2023-08-23T19:42:56.165Z",
    publishedText: "2 days ago",
    videoId: "ob9A8I3cgVg",
    videoUrl: "https://youtube.com/watch?v=ob9A8I3cgVg",
    channelName: "EST Gee",
    channelId: "UCz_QWRP1UzcV10sfML8Gbxw",
    channelUrl: "https://youtube.com/channel/UCz_QWRP1UzcV10sfML8Gbxw",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/ob9A8I3cgVg/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 665001,
    viewsText: "665,001 views",
    duration: 143,
    durationText: "2:23",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Hayami Hana By Raúl",
    description:
      "Por si acaso nunca volvemos hablar,\nY mis ojos favoritos no me vuelven a mirar,\nEsta la hago pa’ cuando te quieras recordar \ndel loquito tuyo que te quería de verdad.\nY no voa' hacerme el...",
    publishedDate: "2023-08-22T17:18:56.165Z",
    publishedText: "13 days ago",
    videoId: "6KF0AmQaGpc",
    videoUrl: "https://youtube.com/watch?v=6KF0AmQaGpc",
    channelName: "Rauw Alejandro",
    channelId: "UC_Av98lDjf5KvFib5elhpYg",
    channelUrl: "https://youtube.com/channel/UC_Av98lDjf5KvFib5elhpYg",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/6KF0AmQaGpc/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 11403625,
    viewsText: "11,403,625 views",
    duration: 328,
    durationText: "5:28",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "V 'Love Me Again' Official MV",
    description:
      "V 'Love Me Again' Official MV\n\n'Layover' Release\n23. 9. 8. 1PM KST | 0AM ET\n💽 Pre-save & pre-order: https://ingrv.es/layover\n\nCredits:\nProducer: MIN HEE JIN\nMusic Video Director: Shin Dongle...",
    publishedDate: "2023-08-22T14:54:56.165Z",
    publishedText: "2 weeks ago",
    videoId: "HYzyRHAHJl8",
    videoUrl: "https://youtube.com/watch?v=HYzyRHAHJl8",
    channelName: "HYBE LABELS",
    channelId: "UC3IZKseVpdzPSBaWxBxundA",
    channelUrl: "https://youtube.com/@HYBELABELS",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/HYzyRHAHJl8/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 46528075,
    viewsText: "46,528,075 views",
    duration: 198,
    durationText: "3:18",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "BigXThaPlug - Whip it (Official Video)",
    description:
      "Follow BigXthaPlug:\nhttps://www.instagram.com/bigxthaplug\nhttps://twitter.com/BigXthaPlugg\nhttps://www.facebook.com/profile.php?id=100063805581381\n\n#BigXthaPlug #BigStepper",
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "KmEtbvCzfrU",
    videoUrl: "https://youtube.com/watch?v=KmEtbvCzfrU",
    channelName: "BigXthaPlug",
    channelId: "UCEJdOGwm6CNtc_kIa_Qjy6A",
    channelUrl: "https://youtube.com/channel/UCEJdOGwm6CNtc_kIa_Qjy6A",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/KmEtbvCzfrU/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 368826,
    viewsText: "368,826 views",
    duration: 134,
    durationText: "2:14",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title:
      "That Mexican OT - Opp or 2 (feat. Maxo Kream) (Official Music Video)",
    description:
      'That Mexican OT - Opp or 2 (feat. Maxo Kream) (Official Music Video)\n\n"Opp or 2" Shot & Edited by DGreenFilmz\n\nStream Lonestar Luchador - https://thatmexicanot.lnk.to/LonestarLuchador\n\n"Lonestar...',
    publishedDate: "2023-08-23T07:42:56.165Z",
    publishedText: "7 days ago",
    videoId: "2FEBBQIevpI",
    videoUrl: "https://youtube.com/watch?v=2FEBBQIevpI",
    channelName: "That Mexican OT",
    channelId: "UC4cvpsB_dAX8i5vdaBB-96w",
    channelUrl: "https://youtube.com/channel/UC4cvpsB_dAX8i5vdaBB-96w",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/2FEBBQIevpI/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 605860,
    viewsText: "605,860 views",
    duration: 166,
    durationText: "2:46",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Maluma, Carin Leon - Según Quién (Official Video)",
    description:
      "Maluma & Carin Leon - Según Quien (Official Video)\n\nMusic:\nApple Music: https://sml.lnk.to/SegunQuien/applemusic\nSpotify: https://sml.lnk.to/SegunQuien/spotify\nAmazon: https://sml.lnk.to/SegunQuie...",
    publishedDate: "2023-08-23T10:06:56.165Z",
    publishedText: "6 days ago",
    videoId: "69lO08ar-mI",
    videoUrl: "https://youtube.com/watch?v=69lO08ar-mI",
    channelName: "Maluma",
    channelId: "UClZuKq2m0Qu-HkopkSBLpEw",
    channelUrl: "https://youtube.com/channel/UClZuKq2m0Qu-HkopkSBLpEw",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/69lO08ar-mI/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 2855798,
    viewsText: "2,855,798 views",
    duration: 150,
    durationText: "2:30",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Call Your Friends",
    description:
      "Provided to YouTube by Alamo\n\nCall Your Friends · Rod Wave\n\nCall Your Friends\n\n℗ 2023 Alamo Records, LLC/Sony Music Entertainment\n\nReleased on: 2023-08-18\n\nComposer: Rodarius Green\nProducer:...",
    publishedDate: "2023-08-23T12:30:56.165Z",
    publishedText: "5 days ago",
    videoId: "YsxF6nYQXBA",
    videoUrl: "https://youtube.com/watch?v=YsxF6nYQXBA",
    channelName: "RodWave",
    channelId: "UCenjunBhBhvKjfDAESnoppw",
    channelUrl: "https://youtube.com/channel/UCenjunBhBhvKjfDAESnoppw",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/YsxF6nYQXBA/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 312786,
    viewsText: "312,786 views",
    duration: 154,
    durationText: "2:34",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "Chris Webby - North Of Richmond (Remix)",
    description:
      "Chris Webby - North Of Richmond (Remix)\n\nOriginal song and inspiration by Oliver Anthony Music.\n\nProduced by JP Da Track\n\nMixed & Mastered by Nox Beatz\n\nShot by Frankie Fire\n\nNo monetization...",
    publishedDate: "2023-08-23T17:18:56.165Z",
    publishedText: "3 days ago",
    videoId: "mlqp-xNUbNE",
    videoUrl: "https://youtube.com/watch?v=mlqp-xNUbNE",
    channelName: "ForTheBurbs",
    channelId: "UCISVviKwSuJLSyLwUKrbP8w",
    channelUrl: "https://youtube.com/channel/UCISVviKwSuJLSyLwUKrbP8w",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/mlqp-xNUbNE/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 383234,
    viewsText: "383,234 views",
    duration: 196,
    durationText: "3:16",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
  {
    title: "V 'Rainy Days' Official MV",
    description:
      "V 'Rainy Days' Official MV\n\n'Layover' Release\n23. 9. 8. 1PM KST | 0AM ET\n💽 Pre-save & pre-order: https://ingrv.es/layover\n\nCredits:\nProducer: MIN HEE JIN\nMusic Video Director: Shin Dongle...",
    publishedDate: "2023-08-22T19:42:56.165Z",
    publishedText: "12 days ago",
    videoId: "yTsINmrAK4I",
    videoUrl: "https://youtube.com/watch?v=yTsINmrAK4I",
    channelName: "HYBE LABELS",
    channelId: "UC3IZKseVpdzPSBaWxBxundA",
    channelUrl: "https://youtube.com/@HYBELABELS",
    thumbnails: [
      {
        quality: "maxres",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/maxres.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "maxresdefault",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/maxresdefault.jpg",
        width: 1280,
        height: 720,
      },
      {
        quality: "sddefault",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/sddefault.jpg",
        width: 640,
        height: 480,
      },
      {
        quality: "high",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/hqdefault.jpg",
        width: 480,
        height: 360,
      },
      {
        quality: "medium",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/mqdefault.jpg",
        width: 320,
        height: 180,
      },
      {
        quality: "default",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/default.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "start",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/1.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "middle",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/2.jpg",
        width: 120,
        height: 90,
      },
      {
        quality: "end",
        url: "https://i.ytimg.com/vi/yTsINmrAK4I/3.jpg",
        width: 120,
        height: 90,
      },
    ],
    views: 24115345,
    viewsText: "24,115,345 views",
    duration: 187,
    durationText: "3:07",
    verified: true,
    creatorOnRise: false,
    isShort: false,
  },
];

$(".dropdown-menu").on("click", function(event) {
  if (event.target.matches(".dropdown-item")) {
    const value = $(event.target).attr("data-type")
    generateCarousel(value);
  }
})
let generateCarousel = function(type){
  $(".carousel-inner").empty();
  fetch(
    `https://youtube-trending.p.rapidapi.com/trending?country=US&type=${type}`,
    {
      headers: {
        "X-RapidAPI-Key": "61e021c72dmshc4db71b199302a4p14684djsnba00d77f9d68",
        "X-RapidAPI-Host": "youtube-trending.p.rapidapi.com",
      },
    }
  )
    .then(function (response) {
      return response.json();
    })
    .then(function (data) {
      for (let i = 0; i < data.length; i++) {
        const thumbnail = data[i].thumbnails[1].url;
        const title = data[i].title;
        const description = data[i].description;
        const link = data[i].videoUrl;
        let markup = `<div class='carousel-item ${i === 0 ? "active" : ""}'>
         <img class="carousel-img" src="${thumbnail}"/>
          <div class="carousel-caption d-md-block">
            <h5 class="title"><a href="${link}">${title}</a></h5>
            <p class="descriptionFont">${description}</p>
         </div>
       </div>`;
        $(".carousel-inner").append(markup);
      }
    });
}
generateCarousel("default");